#!/bin/bash

cpu=$(nproc)
host=$(hostname)

echo $cpu
echo $host

json="{"\""hostname"\"":"\""${host}"\"","\""cpu"\"":${cpu},"\""maxusers"\"":30001,"\""ipscan"\"":"\""eth1"\""}"

echo $json

result=$(curl -s -X PUT -d ${json} http://172.20.4.60:8500/v1/kv/nodes/${host})

echo $result

